services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    restart: always
    expose:
      - "3000"
    networks:
      - app_net

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - frontend-build:/app/dist
    restart: "no" # just used to build
    networks:
      - app_net

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
    volumes:
      - frontend-build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_net
    restart: always

volumes:
  frontend-build:

networks:
  app_net:
    driver: bridge