version: "3.8"

services:
  backend:
    build:
      context: ./Backend
    expose:
      - "3000"
    networks:
      - app_net

  frontend:
    build:
      context: ./Frontend
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
