FROM node:20-bullseye-slim
WORKDIR /app
COPY package*.json tsconfig.json ./
RUN apt-get update && apt-get install -y sqlite3 build-essential && npm install
# RUN npm install
COPY . .
EXPOSE 3000
CMD ["sh", "-c", "npm run migrate && npm run dev"]
# CMD ["npm", "run", "dev"]
