services:
  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile.dev
    volumes:
      - ../Backend:/app
      # - /app/node_modules
      - backend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ../Backend/.env

  frontend:
    build:
      context: ../Frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ../Frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    env_file:
      - ../Frontend/.env
volumes:
  backend_node_modules:
  frontend_node_modules:
