server {
    listen 80;

    client_max_body_size 4m;

    # Serve frontend built files
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.\. {
        return 404;
    }
    location / {
        try_files $uri /index.html;
    }

    # API -> Backend

     location /api/me/avatar {
        client_max_body_size 3m;
        # proxy_request_buffering off;
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /api/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        error_page 400 401 403 404 413 414 431 =200 /api_error.json;
    }
    location = /api_error.json {
        default_type application/json;
        return 200 '{"ok":false,"error":"Bad request"}';
    }

    location /ws/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /static/ {
        proxy_pass http://backend:3000/static/;
        proxy_set_header Host $host;
    }
}
