#HTTP -> HTTPS
server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}

#HTTPS
server {
    listen 433 ssl default_server;
    http2 on;
    server_name _;

    ssl_certificate         /etc/letsencrypt/live/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/current/privkey.pem;

    ssl_trusted_certificate /etc/letsencrypt/live/current/chain.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    # Serve frontend built files
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

        location /api/me/avatar {
        client_max_body_size 2m;
        # proxy_request_buffering off;
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # API -> Backend
    location /api/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /ws/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    location /static/ {
        proxy_pass http://backend:3000/static/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

